# Generated by Django 3.2.9 on 2021-11-23 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Não definido')], max_length=1)),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atletas',
            },
        ),
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esporte', models.CharField(max_length=40)),
                ('modalidade', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Competição',
                'verbose_name_plural': 'Competições',
            },
        ),
        migrations.CreateModel(
            name='Noc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=3, unique=True)),
                ('regiao', models.CharField(max_length=50)),
                ('observacoes', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Noc',
                'verbose_name_plural': 'Nocs',
            },
        ),
        migrations.CreateModel(
            name='Olimpiada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ano', models.IntegerField()),
                ('estacao', models.CharField(choices=[('Summer', 'Verão'), ('Winter', 'Inverno')], max_length=6)),
                ('cidade', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Olimpíada',
                'verbose_name_plural': 'Olimpíadas',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70, unique=True)),
                ('noc', models.ForeignKey(max_length=3, on_delete=django.db.models.deletion.RESTRICT, to='competition_history_app.noc')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
            },
        ),
        migrations.CreateModel(
            name='CompeticaoAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade_atleta', models.IntegerField(null=True)),
                ('altura_atleta', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('peso_atleta', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('medalha', models.CharField(blank=True, choices=[('Golden', 'Ouro'), ('Silver', 'Prata'), ('Bronze', 'Bronze')], max_length=6)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='competition_history_app.atleta')),
                ('competicao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='competition_history_app.competicao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='competicao',
            name='olimpiada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='competition_history_app.olimpiada'),
        ),
    ]
