# Generated by Django 3.2.9 on 2021-11-24 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition_history_app', '0002_alter_atleta_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competicao',
            name='olimpiada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='competition_history_app.olimpiada', to_field='nome'),
        ),
        migrations.AlterField(
            model_name='time',
            name='noc',
            field=models.ForeignKey(max_length=3, on_delete=django.db.models.deletion.RESTRICT, to='competition_history_app.noc', to_field='sigla'),
        ),
    ]
