# Generated by Django 3.2.9 on 2021-11-25 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition_history_app', '0004_alter_competicaoatleta_medalha'),
    ]

    operations = [
        migrations.AddField(
            model_name='competicaoatleta',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='competition_history_app.time'),
        ),
    ]
