# Generated by Django 3.2.9 on 2021-11-25 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition_history_app', '0005_competicaoatleta_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competicaoatleta',
            name='time',
            field=models.ForeignKey(default=94, on_delete=django.db.models.deletion.RESTRICT, to='competition_history_app.time'),
        ),
    ]
