# Generated by Django 3.2.9 on 2021-11-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_history_app', '0006_alter_competicaoatleta_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competicaoatleta',
            name='altura_atleta',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='competicaoatleta',
            name='peso_atleta',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
    ]
